/* ========== STATE ========== */
const state = {
  currentPage: "dashboard",
  selectedSurgery: null,
  isFromHistory: false,
  generatedChecklist: [],
  currentStepIndex: -1,
  surgeryStartTime: null,
  surgeryTimerInterval: null,
  stepTimestamps: [],
  aiInterventions: 0,
  alertCountdownInterval: null,
  alertTimeoutId: null,
  isPaused: false,
  audioCtx: null,
  soundEnabled: true,
  cameraInterval: null,
  surgeryCompleted: false,
  alertAutoSkipped: false,
};

/* ========== DATA ========== */
const surgeries = [
  {
    id: 1,
    patient: {
      name: "Aashish Meena",
      age: 47,
      gender: "Male",
      bloodGroup: "A+",
      mrn: "MRN-2024-08172",
    },
    surgeryType: "Laparoscopic Appendectomy",
    scheduledTime: "09:30 AM",
    status: "active",
    doctor: "Dr. Ashok Seth",
    team: [
      "Dr. Varun Bansal",
      "Nurse R. Sharma",
      "Tech. A. Kumar",
      "Tech. M. Jain",
      "Nurse D. Reddy",
    ],
    room: "OR-3",
    duration: "45–60 min",
    notes: "Acute appendicitis, no prior abdominal surgery",
  },
  {
    id: 2,
    patient: {
      name: "Priya Sharma",
      age: 62,
      gender: "Female",
      bloodGroup: "O-",
      mrn: "MRN-2024-06431",
    },
    surgeryType: "Total Knee Replacement",
    scheduledTime: "11:00 AM",
    status: "active",
    doctor: "Dr. Vinod Joshi",
    team: [
      "Dr. V. K. Kapoor",
      "Nurse M. Patel",
      "Tech. S. Kumar",
      "Tech. P. Agarwal",
      "Nurse J. Nair",
    ],
    room: "OR-1",
    duration: "90–120 min",
    notes: "Osteoarthritis, left knee",
  },
  {
    id: 3,
    patient: {
      name: "Jatin Bhariya",
      age: 35,
      gender: "Male",
      bloodGroup: "B+",
      mrn: "MRN-2024-09284",
    },
    surgeryType: "Open Reduction Internal Fixation",
    scheduledTime: "02:00 PM",
    status: "in-progress",
    doctor: "Dr. Rajeev Bagarhatta",
    team: [
      "Dr. Varun Bansal",
      "Nurse J. Gupta",
      "Tech. R. Singh",
      "Tech. P. Agarwal",
      "Nurse J. Nair",
    ],
    room: "OR-5",
    duration: "60–90 min",
    notes: "Tibial fracture, right leg",
  },
  {
    id: 4,
    patient: {
      name: "Anjali Gupta",
      age: 28,
      gender: "Female",
      bloodGroup: "AB+",
      mrn: "MRN-2024-11045",
    },
    surgeryType: "Laparoscopic Cholecystectomy",
    scheduledTime: "04:30 PM",
    status: "upcoming",
    doctor: "Dr. Ashok Seth",
    team: [
      "Dr. V. K. Kapoor",
      "Nurse C. Verma",
      "Tech. M. Jain",
      "Tech. A. Kumar",
      "Nurse R. Sharma",
    ],
    room: "OR-2",
    duration: "45–75 min",
    notes: "Gallstones, symptomatic",
  },
  {
    id: 5,
    patient: {
      name: "Ravi Kumar",
      age: 55,
      gender: "Male",
      bloodGroup: "A-",
      mrn: "MRN-2024-05012",
    },
    surgeryType: "Coronary Artery Bypass Grafting",
    scheduledTime: "Yesterday, 08:00 AM",
    status: "completed",
    doctor: "Dr. Vinod Joshi",
    team: [
      "Dr. Varun Bansal",
      "Nurse D. Reddy",
      "Tech. P. Agarwal",
      "Tech. S. Kumar",
      "Nurse M. Patel",
    ],
    room: "OR-1",
    duration: "180–240 min",
    notes: "Triple vessel disease",
    completedDuration: "195 min",
    aiInterventions: 2,
    missedSteps: 0,
  },
  {
    id: 6,
    patient: {
      name: "Shikahr Sonwal",
      age: 71,
      gender: "Male",
      bloodGroup: "O+",
      mrn: "MRN-2024-03891",
    },
    surgeryType: "Hip Hemiarthroplasty",
    scheduledTime: "Yesterday, 01:00 PM",
    status: "completed",
    doctor: "Dr. Rajeev Bagarhatta",
    team: [
      "Dr. V. K. Kapoor",
      "Nurse J. Nair",
      "Tech. R. Singh",
      "Tech. M. Jain",
      "Nurse C. Verma",
    ],
    room: "OR-4",
    duration: "60–90 min",
    notes: "Femoral neck fracture, left hip",
    completedDuration: "78 min",
    aiInterventions: 1,
    missedSteps: 1,
  },
];

const patients = [
  // Additional patients not yet scheduled for surgery
];

const lapAppendectomySteps = [
  {
    id: 1,
    name: "Patient Identity & Site Verification",
    duration: 3000,
    alert: null,
    voice: "Patient identity and surgical site verified",
  },
  {
    id: 2,
    name: "Pre-operative Checklist Review",
    duration: 2500,
    alert: null,
    voice: "Pre-operative checklist completed",
  },
  {
    id: 3,
    name: "Anesthesia Induction",
    duration: 4000,
    alert: null,
    voice: "Patient anesthetized successfully",
  },
  {
    id: 4,
    name: "Patient Positioning",
    duration: 2000,
    alert: null,
    voice: "Patient positioned correctly",
  },
  {
    id: 5,
    name: "Surgical Site Preparation",
    duration: 3000,
    alert: null,
    voice: "Surgical site prepared and draped",
  },
  {
    id: 6,
    name: "Initial Incision",
    duration: 3500,
    alert: null,
    voice: "Initial incision made",
  },
  {
    id: 7,
    name: "Port Placement",
    duration: 4500,
    alert: null,
    voice: "Trocar ports placed successfully",
  },
  {
    id: 8,
    name: "Insufflation",
    duration: 2500,
    alert: null,
    voice: "Pneumoperitoneum established",
  },
  {
    id: 9,
    name: "Exploration",
    duration: 3000,
    alert: null,
    voice: "Abdominal cavity explored",
  },
  {
    id: 10,
    name: "Appendix Identification",
    duration: 3500,
    alert: null,
    voice: "Appendix identified and isolated",
  },
  {
    id: 11,
    name: "Mesenteric Dissection",
    duration: 5000,
    alert: null,
    voice: "Mesenteric vessels dissected",
  },
  {
    id: 12,
    name: "Appendix Ligation",
    duration: 4000,
    alert: {
      type: "critical",
      message:
        "AI Alert: Appendix base ligation critical - ensure complete occlusion",
      voice: "Critical: Verify appendix base ligation",
    },
    voice: "Appendix base ligated",
  },
  {
    id: 13,
    name: "Appendix Division",
    duration: 2500,
    alert: null,
    voice: "Appendix divided",
  },
  {
    id: 14,
    name: "Specimen Retrieval",
    duration: 3000,
    alert: null,
    voice: "Specimen retrieved",
  },
  {
    id: 15,
    name: "Hemostasis Check",
    duration: 3500,
    alert: null,
    voice: "Hemostasis confirmed",
  },
  {
    id: 16,
    name: "Irrigation & Suction",
    duration: 2500,
    alert: null,
    voice: "Cavity irrigated and suctioned",
  },
  {
    id: 17,
    name: "Final Inspection",
    duration: 3000,
    alert: null,
    voice: "Final inspection completed",
  },
  {
    id: 18,
    name: "Desufflation",
    duration: 2000,
    alert: null,
    voice: "Pneumoperitoneum released",
  },
  {
    id: 19,
    name: "Port Removal",
    duration: 2500,
    alert: null,
    voice: "Ports removed",
  },
  {
    id: 20,
    name: "Fascial Closure",
    duration: 4000,
    alert: null,
    voice: "Fascial defects closed",
  },
  {
    id: 21,
    name: "Skin Closure",
    duration: 3000,
    alert: null,
    voice: "Skin closed",
  },
  {
    id: 22,
    name: "Dressing Application",
    duration: 2000,
    alert: null,
    voice: "Wound dressed",
  },
  {
    id: 23,
    name: "Post-operative Verification",
    duration: 2500,
    alert: null,
    voice: "Procedure completed successfully",
  },
];
